Repository FlourishHealth/ferns-api, pull requests merged in 2024-08, with the labels that each got.

#413 Add DateOnly schema type
  package.json
  src/expressServer.ts
  src/plugins.test.ts
  src/plugins.ts
  yarn.lock
Labels: dependencies, enhancement, Review effort [1-5]: 3, Tests

#416 Upgrade open api generator and test with custom
  .vscode/settings.json
  package.json
  src/__snapshots__/openApi.test.ts.snap
  src/expressServer.ts
  src/openApi.test.ts
  yarn.lock
Labels: dependencies, enhancement, Review effort [1-5]: 3, Tests

#419 Fix up querying for DateOnly field
  src/plugins.test.ts
  src/plugins.ts
Labels: enhancement, Review effort [1-5]: 2, Tests

#420 Auth changes and logging
  src/auth.test.ts
  src/auth.ts
  src/expressServer.ts
Labels: enhancement, Review effort [1-5]: 3, Bug fix
