Repository FlourishHealth/ferns-api, pull requests merged in 2024-03, with the labels that each got.

#353 Add more error detail for Sentry
  src/errors.ts
Labels: enhancement, Possible security concern, Review effort [1-5]: 2

#360 Upgrade mongoose to v8
  package.json
  yarn.lock
Labels: enhancement, Review effort [1-5]: 1

#352 Move permissions into middleware
  jest.config.js
  src/api.test.ts
  src/api.ts
  src/permissions.ts
Labels: enhancement, Review effort [1-5]: 3

#365 Allow setting sentry environment
  src/expressServer.ts
Labels: enhancement, Review effort [1-5]: 1

#368 Add logging around tokens
  src/auth.ts
Labels: enhancement, Review effort [1-5]: 2
