Repository FlourishHealth/ferns-api, pull requests merged in 2024-06, with the labels that each got.

#395 Return error if jwt cannot be decoded properly or has an error
  src/auth.test.ts
  src/auth.ts
Labels: Review effort [1-5]: 2, Tests, Bug fix

#394 Customizable token expirations and check for token expirations
  src/auth.test.ts
  src/auth.ts
  src/expressServer.ts
Labels: enhancement, Review effort [1-5]: 2, Tests

#401 update send to slack function
  src/expressServer.ts
Labels: enhancement, Review effort [1-5]: 2, Bug fix
